server:
  port: 8080
  address: 127.0.0.1
  sessionTimeout: 30
  contextPath: /
---
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: jfa
      authenticationDatabase: jfa
---
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.jfa.data.entity
---
spring:
  datasource:
    name: bonddb
    url: jdbc:oracle:thin:@localhost:1521:bonddb
    username: bond
    password: zya198349
    driverClassName: oracle.jdbc.OracleDriver
